apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncflow-ingress
  namespace: syncflow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.syncflow.novasynctechnologies.com
      secretName: syncflow-tls
  rules:
    - host: api.syncflow.novasynctechnologies.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: syncflow-api
                port:
                  number: 80
