apiVersion: v1
kind: Service
metadata:
  name: syncflow-api
  namespace: syncflow
  labels:
    app: syncflow-api
spec:
  type: ClusterIP
  selector:
    app: syncflow-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
